export  class Yourdrs {
  public constructor (
    // public appt date: Date,
    // public auth status: string,
    // public case: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,
    // public pname: string,

    // "appt date": "27/12/2005",
    // "auth status": "P",
    // "case":"Y18047621_1",
    // "mop":"NA",
    // "sup bilstatus":"pending",
    // "check in time":"NA",
    // "pat name":"abc",
    // "appt cre date":"25/11/2020",
    // "provider":"Dr ky",
    // "ver status":"P",
    // "location":"hema",
    // "case detail":"worker com",
    // "appt status":"visit",
    // "dic type":"medical record",
    // "ass status":"N/A",
    // "pos loc":"hema 54 dean",
    // "vid session":"NA",
    // "dic status":"dictation is start",
    // "bill status":"pending",
    // "appt type":"PT"
  ) {}
}
